services:
  - type: web
    name: videogame-api
    env: dotnet
    rootDir: VideoGameAPI
    buildCommand: dotnet publish VideoGameAPI/VideoGameAPI.csproj -c Release -o out
    startCommand: dotnet out/VideoGameAPI.dll
    envVars:
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: true