services:
  - type: web
    name: videogame-api
    env: docker
    rootDir: VideoGameAPI
    plan: free
    autoDeploy: true
    healthCheckPath: /weatherforecast
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: videogame-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production